# Generated by Django 5.1.7 on 2025-09-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a full name', max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age in years')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Select gender', max_length=1)),
                ('location', models.CharField(help_text='City,State or detailes location', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
